// <auto-generated />
using CRUD.Infra.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CRUD.Infra.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210928212645_MigracaoInicial")]
    partial class MigracaoInicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CRUD.Domain.Entities.CAD_cargo", b =>
                {
                    b.Property<int>("car_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("car_nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("car_id");

                    b.ToTable("CAD_cargo");
                });

            modelBuilder.Entity("CRUD.Domain.Entities.CAD_contato", b =>
                {
                    b.Property<int>("con_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("car_id")
                        .HasColumnType("int");

                    b.Property<string>("con_ativo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("con_dtNasc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("con_nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("con_sexo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("con_telefone")
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("con_id");

                    b.HasIndex("car_id");

                    b.ToTable("CAD_contato");
                });

            modelBuilder.Entity("CRUD.Domain.Entities.CAD_contato", b =>
                {
                    b.HasOne("CRUD.Domain.Entities.CAD_cargo", "cAD_cargo")
                        .WithMany("cAD_contato")
                        .HasForeignKey("car_id")
                        .HasConstraintName("FK_CAD_contato_CAD_cargo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("cAD_cargo");
                });

            modelBuilder.Entity("CRUD.Domain.Entities.CAD_cargo", b =>
                {
                    b.Navigation("cAD_contato");
                });
#pragma warning restore 612, 618
        }
    }
}
